name: Deploy meus-apps-frontend

on:
  # pull_request:
  push:
    branches:
      - main #
    # types:
    #   - closed

jobs:
  build_and_publish:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Config git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Instalar dependÃªncias
        run: npm ci

      - name: Criar release com release-it
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Obter tag da release
        id: extract_tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Construir e publicar imagem
        run: |
          docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -f ./infra/docker/Dockerfile.prod --build-arg VITE_SERVICE_VERSION=${{ env.TAG }} --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} --tag ghcr.io/oondemand/meus-apps-frontend:${{ env.TAG }}-prod .
          docker push ghcr.io/oondemand/meus-apps-frontend:${{ env.TAG }}-prod

      - name: Criar kubeconfig
        run: |
          mkdir -p "${HOME}/.kube"
          curl -s -H "Authorization: Bearer ${{secrets.DO_ACCESS_TOKEN}}" "${{secrets.DO_CLUSTER_AUTHENTICATION_URL}}" > "$HOME/.kube/config"

      - name: Usar contexto do cluster
        run: |
          kubectl config use-context ${{ secrets.CLUSTER }}

      - name: ðŸš€ Substituir variÃ¡veis no deployment.yml e aplicar no cluster
        run: |
          envsubst < infra/kubernetes/deployment.yaml | kubectl apply -f -

        env:
          IMAGE_TAG: ${{ env.TAG }}
